#------------------------------------------------------------------------------
#Name:      Makefile
#Project:   xmlBlaster
#Comment:   Makefile for sub directories
#------------------------------------------------------------------------------

SUB_DIRS = java/org/xmlBlaster/util idl java/org/xmlBlaster

include $(XMLBLASTER_HOME)/make/make.h
include $(XMLBLASTER_HOME)/make/makeSubDirs.h
