#!/bin/sh

#Set this in your environment:
#JAVA_HOME=/usr/jdk1.2.2
if [ ${JAVA_HOME:=""} = "" ] ; then
   echo "ERROR: Please set the environment variable JAVA_HOME"
   exit
fi

#CLASSPATH=$JAVA_HOME/lib/tools.jar:lib/ant/ant.jar:lib/ant/cpptasks.jar:lib/ant/ant-contrib.jar:lib/ant/xerces.jar:lib/ant/optional.jar:lib/junit.jar:lib/ant/xalan.jar:lib/ant/xml-apis.jar:lib/ant/j2me-ant-0.9.0.jar:lib/ant/bsf.jar:lib/batik/js.jar

OWNCLASSPATH=$JAVA_HOME/lib/tools.jar
for i in `find lib/ant -name "*.jar"` ; do
  OWNCLASSPATH=$OWNCLASSPATH:$i
done
OWNCLASSPATH=$OWNCLASSPATH:lib/batik/js.jar

# Set in your $HOME/build.properties
# build.compiler=jikes  or  modern  or classic

"$JAVA_HOME/bin/java" -Xmx256m -Dant.home="$XMLBLASTER_HOME" -classpath "$OWNCLASSPATH" org.apache.tools.ant.Main $@

# end of file
