/*--------------------------------------------------------------------------
Name:      PropertyDef.h
Project:   xmlBlaster.org
Copyright: xmlBlaster.org, see xmlBlaster-LICENSE file
Comment:   Handling the Client data, defines operating system specific stuff.
           This file is generated by org.xmlBlaster.util.cpp.SetCCProperties
---------------------------------------------------------------------------*/

#ifndef _UTIL_PROPERTYDEF_H
#define _UTIL_PROPERTYDEF_H

#define FILE_SEP "/"
#define PATH_SEP ":"

#endif
