# Todo: use a global VERSION file for java, C++ and all other languages
VERSION = 0.79c
SRC_DIR =$(XMLBLASTER_HOME)/src/c++
include $(SRC_DIR)/$(CORBA_CPP).def
IDL_DIR    =$(XMLBLASTER_HOME)/src/java/org/xmlBlaster/protocol/corba
LIB_DIR    =$(XMLBLASTER_HOME)/lib
GEN_DIR    =$(SRC_DIR)/generated
CLIENT_DIR =$(SRC_DIR)/client
UTIL_DIR   =$(SRC_DIR)/util
JUTIL_DIR  =$(SRC_DIR)/jutil
SHARED_LIB =xmlBlasterClient
SHARED_LIB_NAME =lib$(SHARED_LIB).so
TEST_DIR   =$(XMLBLASTER_HOME)/testsuite/c++
BIN_DIR    =$(TEST_DIR)/bin
XMLCPP_INC =-I$(XMLCPP_HOME)/include
XMLCPP_LIB =-L$(XMLCPP_HOME)/lib -lxerces-c$(XMLCPP_VER) -lpthread
CLIENT_OBJ =$(CLIENT_DIR)/CorbaConnection.o $(UTIL_DIR)/CompatibleCorba.o $(UTIL_DIR)/Log.o

MKDIR      =mkdir
RMDIR      =rm -r
RM         =rm -f
SYMLINK    =ln -s
CD         =cd
CC         =g++
LD         =g++ -shared
SLIB_ATTR  =chmod a-w
