# Please read 
#   http://www.cs.indiana.edu/~chiuk/misc_tech_notes/#comp_vers
# about settings for UNIX flavours


# Todo: use a global VERSION file for java, C++ and all other languages
VERSION = 0.84
SRC_DIR =$(XMLBLASTER_HOME)/src/c++
include $(SRC_DIR)/$(CORBA_CPP).def
IDL_DIR    =$(XMLBLASTER_HOME)/src/java/org/xmlBlaster/protocol/corba
LIB_DIR    =$(XMLBLASTER_HOME)/lib
GEN_DIR    =$(SRC_DIR)/generated
CLIENT_DIR =$(SRC_DIR)/client
UTIL_DIR   =$(SRC_DIR)/util
JUTIL_DIR  =$(SRC_DIR)/jutil
SHARED_LIB =xmlBlasterClient
TEST_DIR   =$(XMLBLASTER_HOME)/testsuite/src/c++
BIN_DIR    =$(TEST_DIR)/bin
XMLCPP_INC =-I$(XMLCPP_HOME)/include -I$(XMLCPP_HOME)/include/xercesc
XMLCPP_LIB =-L$(XMLCPP_HOME)/lib -lxerces-c$(XMLCPP_VER) -lpthread
CLIENT_OBJ =$(CLIENT_DIR)/CorbaConnection.o $(UTIL_DIR)/CompatibleCorba.o $(UTIL_DIR)/Log.o

# Settings for Linux with gcc:
MKDIR      =mkdir
RMDIR      =rm -r
RM         =rm -f
SYMLINK    =ln -s
CD         =cd
CFLAGS     =-g -Wall -Wstrict-prototypes -Wimplicit-int -Werror-implicit-function-declaration
CC         =g++ $(CFLAGS)
# To avoid setting of LD_LIBRARY_PATH:
SHARED_LIB_FLAGS=-Wl,-rpath=$(LIB_DIR) -Wl,-rpath=$(XMLCPP_HOME)/lib -Wl,-rpath=$(CORBACPP_HOME)/lib
CL         =g++ $(CFLAGS) $(SHARED_LIB_FLAGS)
SLIB_FLAGS =-fpic
LD         =g++ -shared $(CFLAGS)
SLIB_ATTR  =chmod a-w
SHARED_LIB_NAME =lib$(SHARED_LIB).so
